### ISSUE TITLE
Block Visibility - If the custom field is empty, then don't display the block.  

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeedwp/tour-operator#372]
### Description

In the Tour Operator plugin, we need to ensure that custom field blocks for the single post types (Accommodation, Tours, and Destinations) are only displayed if the respective field is not empty. If a field is empty, the entire group/block should be hidden on the frontend using CSS classes.

#### For Tours:
- price
- duration
- travel-style
- destination-to-tour
- departs-from
- ends-in
- gallery
- itinerary
- single-supplement
- group-size
- best-time-to-visit
- booking-validity-start
- included
- not-included

#### For Accommodation:
- price
- rating
- number-of-rooms
- check-in-time
- check-out-time
- minimum-child-age
- destination-to-accommodation
- spoken-languages
- travel-style
- accommodation-type
- suggested-visitor-types
- special-interests
- gallery
- rooms
- included
- not-included
- facilities
- single-supplement

#### For Destinations:
- travel-style
- best-time-to-visit
- electricity
- banking
- cuisine
- climate
- transport
- dress
- health
- safety
- visa
- general
- gallery

If any of the above fields are empty for a single post type, the corresponding block should not be displayed on the frontend.

### Bugherd Links
- https://www.bugherd.com/projects/218796/tasks/66
- https://www.bugherd.com/projects/218796/tasks/61
- https://www.bugherd.com/projects/218796/tasks/60
- https://www.bugherd.com/projects/218796/tasks/57

**Comment by ZaredRogers** [comment]
### Issues with Single Tour

**lsx-_meta-field_-wrapper additional CSS class not working for:**

- duration
- travel-style
- destination-to-tour
- departs-from
- ends-in
- gallery
- itinerary
- single-supplement
- group-size
- best-time-to-visit
- booking-validity-start


### Screenshot
![Image](https://github.com/user-attachments/assets/a95ebf8a-ed37-4d77-8ff1-fd14e64b2a25)

### Links

- https://tour-operator.lsx.design/wp-admin/site-editor.php?postType=wp_template&postId=lsx-tour-operator%2F%2Fsingle-tour&canvas=edit
- https://tour-operator.lsx.design/tour/empty-tour/
- https://tour-operator.lsx.design/wp-admin/post.php?post=61550&action=edit

**Comment by ZaredRogers** [comment]
### Outstanding Issues

Most of the blocks work now, with the exception of:

- gallery
- included
- not_included

We also need a way to hide the entire Included and Not Included box if neither are present

**Comment by krugazul** [comment]
Final Bugs completed, closing the task.
