### ISSUE TITLE
Single Country Regions Custom Query Loop

### ISSUE THREAD

**Issue by ZaredRogers** [lightspeedwp/tour-operator#384]
### Description:

The Single Country template will include a Regions section, displaying the regions that belong to the parent country. These regions are structured as child elements in the file hierarchy and will be displayed using the **Destination Card** pattern. If there are more than 3 regions, the section should be displayed as a carousel. If there are no regions associated with the country, the Regions section should not display at all.

### Requirements:

- [x] Develop a **Regions Section** for the Single Country template that displays the regions as child elements of the parent country.
   - The regions will be dynamically populated based on the country they belong to.

- [x] Display the regions using the **Destination Card** pattern.
   - Ensure that the cards are consistent with the overall design and structure of the Destination Card pattern.

- [x] Hide the Regions section entirely if there are no regions associated with the country.

### Acceptance Criteria:
- [x] A Regions Section is added to the Single Country template, displaying regions as child elements of the country.
- [x] Regions are displayed using the Destination Card pattern.
- [x] The Regions section does not display if no regions are associated with the country.
- [x] The section is fully responsive and displays correctly across devices.

Resources:
- [Figma File](https://www.figma.com/design/1wiwltz5a0og0YIoKsuPmn/LSX-Tour-Operator-Design-System?m=auto&node-id=6976-61726&t=LGUcPpLNrjR2p6VG-1)

### Images:

<img width="650" alt="LSX Tour Operator Design System 2024-10-10 at 2 37 32 PM" src="https://github.com/user-attachments/assets/d0311bbb-71b2-400e-9b72-66205dfc2124">

### Additional Notes:
- Test to ensure that the correct regions are displayed based on the parent country, and that the Destination Card pattern is implemented consistently.
- Verify that the section hides correctly when no regions are available.

### Information Needed
- [x] @krugazul to add size and time estimate and add sprint

**Comment by krugazul** [comment]
I have removed the carousel functionality requirement, that is being tracked in [https://github.com/lightspeedwp/tour-operator/issues/366](https://github.com/lightspeedwp/tour-operator/issues/366)
