### ISSUE TITLE
PHP Fatal Error and Syncing Issue in LSX Wetu Importer for Accommodation

### ISSUE THREAD

**Issue by ZaredRogers** [lightspeedwp/tour-operator#444]
### Description
A client reported that accommodations do not sync in the LSX Wetu Importer plugin. The list fails to load and shows an indefinite spinner, indicating it cannot retrieve data from WETU.

After examining the PHP log, we found a fatal error around the same time as the reported issue.

### Error Details
- **Error Type**: PHP Fatal Error: Uncaught TypeError
- **Cause**: Incompatible types were added (string + int)
- **File**: `/wp-content/plugins/lsx-importer-for-wetu/classes/class-lsx-wetu-importer-accommodation.php`
- **Line**: 361

### Steps to Reproduce
1. Attempt to sync accommodation data with WETU via the LSX Wetu Importer.
2. Observe if the spinner remains indefinitely and no data is fetched.

### Expected Behavior
Accommodation data should sync correctly and load the list without errors or indefinite loading.

### Action Items
- **Error Resolution**: Investigate the code on line 361 to address the TypeError by ensuring data type compatibility.
- **Client Coordination**: Request additional details from the client if necessary to replicate the issue.
- **Deployment Preparation**: Verify the fix before deploying to the production server.

**Comment by krugazul** [comment]
@ZaredRogers  this issue was fixed in the following commit. [072a4fda](https://github.com/lightspeedwp/wetu-importer/commit/072a4fda25d7f9b1d0982a25678816e485e5e928)
